In [3]:
from PIL import Image
from numpy import asarray

import os

In [26]:
def vectorTrain(path):

    dict_images = {}
    for idx in range(10):

        arq_names = os.listdir(f"{path}/{idx}/")
        list_arqs = list()
        for arq in arq_names:
            path_arq = path + str(idx) + "/" + arq
            img = Image.open(path_arq)
            array = asarray(Image.fromarray(asarray(img)).resize((13,26)))
            list_arqs.append(array)
        dict_images[f"{idx}"] = list_arqs

    return dict_images

In [27]:
images_dict = vectorTrain("/UTFPR/InteligenciaComputacional/InteligenciaComputacional/treino/teste/")


In [28]:
print(images_dict["5"][1])

[[ 92   0   0   0   0   0   0  92]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   1  72  81  81  77 167]
 [  0   0   3 214 239 239 255 255]
 [  0   0   0   3   3   3 145 255]
 [  0   0   0   0   0   0   3 177]
 [  0   0   0   0   0   0   0  55]
 [  0   0   0   0   0   0   0   0]
 [ 21   0  19 183 183  25   0   0]
 [216 137 209 255 255 141   0   0]
 [119  58 231 255 255 144   0   0]
 [  0   0  38 214 214  43   0   0]
 [  0   0   0   2   2   0   0   0]
 [ 32   0   0   0   0   0   0  32]
 [220  36   0   0   0   0  36 220]]
